package appstrings

const (
	UNKNOWN   = "UNKNOWN"
	USER_TYPE = "USER_TYPE"

	UNKNOWN_SOURCE = "UNKNOWN_SOURCE"
	GIN_SOURCE     = "GIN_SOURCE"

	SQLLITE_DIALECT = "SQLLITE_DIALECT"
	UNKNOWN_DIALECT = "UNKNOWN_DIALECT"
)
